Repository patchlevel/event-sourcing, pull requests merged in 2021-12, with the labels that each got.

#106 refactor aggregate changed for better psalm supprt
  README.md
  baseline.xml
  phpcs.xml.dist
  phpstan-baseline.neon
  src/Aggregate/AggregateChanged.php
  src/Aggregate/AggregateRoot.php
  src/Aggregate/SnapshotableAggregateRoot.php
  src/EventBus/DefaultEventBus.php
  src/EventBus/EventBus.php
  src/EventBus/Listener.php
  src/EventBus/SymfonyEventBus.php
  src/Pipeline/EventBucket.php
  src/Pipeline/Middleware/ClassRenameMiddleware.php
  src/Pipeline/Middleware/ReplaceEventMiddleware.php
  src/Projection/DefaultProjectionRepository.php
  src/Projection/Projection.php
  src/Projection/ProjectionRepository.php
  src/Store/CorruptedMetadata.php
  src/Store/DoctrineStore.php
  src/Store/MultiTableStore.php
  src/Store/SingleTableStore.php
  src/Store/Store.php
  src/WatchServer/WatchServer.php
  tests/Integration/BasicImplementation/Events/ProfileCreated.php
  tests/Integration/BasicImplementation/Projection/ProfileProjection.php
  tests/Integration/Pipeline/Events/NewVisited.php
  tests/Integration/Pipeline/Events/OldVisited.php
  tests/Integration/Pipeline/Events/PrivacyAdded.php
  tests/Integration/Pipeline/Events/ProfileCreated.php
  tests/Unit/Fixture/MessagePublished.php
  tests/Unit/Fixture/ProfileCreated.php
  tests/Unit/Fixture/ProfileVisited.php
  tests/Unit/Pipeline/Middleware/ReplaceEventMiddlewareTest.php
  tests/Unit/Pipeline/Target/ProjectionTargetTest.php
  tests/Unit/Projection/DefaultProjectionRepositoryTest.php
Labels: BC-Break

#119 split repository code into two classes (default & snapshot)
  README.md
  docs/repository.md
  docs/snapshots.md
  phpstan-baseline.neon
  src/Pipeline/Pipeline.php
  src/Repository/DefaultRepository.php
  src/Repository/Repository.php
  src/Repository/SnapshotRepository.php
  tests/Integration/BasicImplementation/BasicIntegrationTest.php
  tests/Integration/Pipeline/PipelineChangeStoreTest.php
  tests/Unit/Repository/DefaultRepositoryTest.php
  tests/Unit/Repository/SnapshotRepositoryTest.php
Labels: BC-Break

#135 removed php7.4, added support php8.1
  .github/workflows/coding-standard.yml
  .github/workflows/mutation-tests.yml
  .github/workflows/phpstan.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
  composer.json
  composer.lock
  src/Aggregate/ApplyMethodNotFound.php
  src/Aggregate/NonStrictApplyMethod.php
  src/Aggregate/StrictApplyMethod.php
  src/Console/EventPrinter.php
  src/Console/InputHelper.php
  src/Console/InvalidArgumentGiven.php
  src/Pipeline/Middleware/ClassRenameMiddleware.php
  src/Projection/DefaultProjectionRepository.php
  src/Repository/DefaultRepository.php
  src/Repository/SnapshotRepository.php
  src/Schema/StoreNotSupported.php
  src/Store/DoctrineStore.php
  src/Store/MultiTableStore.php
  src/Store/SingleTableStore.php
Labels: enhancement, dependencies

#137 add recorded clock trait
  src/Aggregate/ClockRecordDate.php
  tests/Unit/Aggregate/AggregateChangedWithClockTest.php
  tests/Unit/Fixture/ProfileVisitedWithClock.php
Labels: enhancement

#145 fixed php version to 7.4 and 8.0
  composer.json
  composer.lock
Labels: bug, dependencies

#144 set required php version to fixed minor versions
  .github/workflows/coding-standard.yml
  .github/workflows/mutation-tests.yml
  .github/workflows/phpstan.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
  composer.json
  composer.lock
Labels: dependencies

#147 upgrade psr packages
  composer.json
  composer.lock
  tests/Unit/Snapshot/Psr6SnapshotStoreTest.php
Labels: dependencies

#152 add cli, tools and features docs
  README.md
  composer.json
  docs/cli.md
  docs/tests.md
  docs/tools.md
Labels: documentation

#153 add install instructions and listener order information
  README.md
  docs/cli.md
  docs/event_bus.md
Labels: documentation
