Repository patchlevel/event-sourcing, pull requests merged in 2022-06, with the labels that each got.

#259 Silence socket warnings for DefaultWatchServerClient
  src/WatchServer/DefaultWatchServerClient.php
Labels: bug

#267 rename serialized name into normalized name
  src/Attribute/NormalizedName.php
  src/Metadata/AggregateRoot/AttributeAggregateRootMetadataFactory.php
  src/Metadata/Event/AttributeEventMetadataFactory.php
  tests/Unit/Metadata/Event/AttributeEventMetadataFactoryTest.php
Labels: enhancement

#273 add template annotation on message
  src/EventBus/DefaultEventBus.php
  src/EventBus/Message.php
Labels: enhancement

#280 Allow to pass upcaster
  src/Serializer/DefaultEventSerializer.php
Labels: enhancement

#279 finish docs for 2.0
  README.md
  docs/pages/aggregate.md
  docs/pages/cli.md
  docs/pages/event_bus.md
  docs/pages/events.md
  docs/pages/getting_started.md
  docs/pages/message_decorator.md
  docs/pages/outbox.md
  docs/pages/pipeline.md
  docs/pages/projection.md
  docs/pages/repository.md
  docs/pages/snapshots.md
  docs/pages/store.md
  docs/pages/upcasting.md
  docs/pages/watch_server.md
Labels: documentation
