Repository patchlevel/event-sourcing, pull requests merged in 2022-04, with the labels that each got.

#209 rename record method to recordThat
  README.md
  docs/aggregate.md
  docs/faq.md
  src/Aggregate/AggregateRoot.php
  tests/Benchmark/BasicImplementation/Aggregate/Profile.php
  tests/Integration/BasicImplementation/Aggregate/Profile.php
  tests/Integration/Pipeline/Aggregate/Profile.php
  tests/Unit/Fixture/Profile.php
  tests/Unit/Fixture/ProfileInvalid.php
  tests/Unit/Fixture/ProfileWithSnapshot.php
  tests/Unit/Fixture/ProfileWithSuppressAll.php
Labels: BC-Break

#200 Make class name in apply attribute optional
  README.md
  baseline.xml
  composer.json
  composer.lock
  src/Attribute/Apply.php
  src/EventBus/Message.php
  src/Metadata/AggregateRoot/ArgumentTypeIsMissing.php
  src/Metadata/AggregateRoot/ArgumentTypeIsNotAClass.php
  src/Metadata/AggregateRoot/AttributeAggregateRootMetadataFactory.php
  src/Metadata/AggregateRoot/DuplicateEmptyApplyAttribute.php
  src/Metadata/AggregateRoot/MixedApplyAttributeUsage.php
  tests/Benchmark/BasicImplementation/Aggregate/Profile.php
  tests/Unit/Fixture/NameChanged.php
  tests/Unit/Fixture/Profile.php
  tests/Unit/Fixture/ProfileWithBrokenApplyBothUsage.php
  tests/Unit/Fixture/ProfileWithBrokenApplyIntersection.php
  tests/Unit/Fixture/ProfileWithBrokenApplyMultipleApply.php
  tests/Unit/Fixture/ProfileWithBrokenApplyNoType.php
  tests/Unit/Fixture/ProfileWithEmptyApply.php
  tests/Unit/Metadata/Aggregate/AttributeAggregateMetadataFactoryTest.php
Labels: enhancement

#211 aggregate root registry
  README.md
  docs/aggregate.md
  src/Aggregate/AggregateRoot.php
  src/Attribute/Aggregate.php
  src/Attribute/SuppressMissingApply.php
  src/Console/Command/ShowCommand.php
  src/Metadata/AggregateRoot/AggregateRootClassNotRegistered.php
  src/Metadata/AggregateRoot/AggregateRootMetadata.php
  src/Metadata/AggregateRoot/AggregateRootNameNotRegistered.php
  src/Metadata/AggregateRoot/AggregateRootRegistry.php
  src/Metadata/AggregateRoot/AggregateRootRegistryFactory.php
  src/Metadata/AggregateRoot/AttributeAggregateRootMetadataFactory.php
  src/Metadata/AggregateRoot/AttributeAggregateRootRegistryFactory.php
  src/Metadata/AggregateRoot/NoAggregateRoot.php
  src/Metadata/ClassFinder.php
  src/Metadata/Event/AttributeEventRegistryFactory.php
  src/Metadata/Event/ClassIsNotAnEvent.php
  src/Metadata/Event/EventPropertyMetadata.php
  src/Metadata/Projection/AttributeProjectionMetadataFactory.php
  src/Metadata/Projection/ProjectionHandleMetadata.php
  src/Metadata/Projection/ProjectionMetadata.php
  src/Store/AggregateNotDefined.php
  src/Store/MultiTableStore.php
  src/Store/SingleTableStore.php
  tests/Benchmark/BasicImplementation/Aggregate/Profile.php
  tests/Benchmark/LoadEventsBench.php
  tests/Benchmark/LoadEventsWithSnapshotsBench.php
  tests/Benchmark/WriteEventsBench.php
  tests/Integration/BasicImplementation/Aggregate/Profile.php
  tests/Integration/BasicImplementation/BasicIntegrationTest.php
  tests/Integration/Pipeline/Aggregate/Profile.php
  tests/Integration/Pipeline/PipelineChangeStoreTest.php
  tests/Unit/Attribute/SuppressMissingApplyTest.php
  tests/Unit/Console/Command/ShowCommandTest.php
  tests/Unit/Fixture/Profile.php
  tests/Unit/Metadata/Aggregate/AggregateRootRegistryTest.php
  tests/Unit/Metadata/Aggregate/AttributeAggregateRootRegistryFactoryTest.php
  tests/Unit/Store/MultiTableStoreTest.php
  tests/Unit/Store/SingleTableStoreTest.php
Labels: enhancement, BC-Break

#212 remove duplicated code in projection target
  src/Pipeline/Target/ProjectionTarget.php
Labels: enhancement

#213 snapshot refactoring
  composer.json
  composer.lock
  docs/repository.md
  docs/snapshots.md
  src/Aggregate/AggregateRoot.php
  src/Attribute/Snapshot.php
  src/Metadata/AggregateRoot/AggregateRootMetadata.php
  src/Metadata/AggregateRoot/AttributeAggregateRootMetadataFactory.php
  src/Metadata/AggregateRoot/ClassIsNotAnAggregate.php
  src/Repository/DefaultRepository.php
  src/Repository/SnapshotRebuildFailed.php
  src/Repository/SnapshotRepository.php
  src/Snapshot/Adapter/InMemorySnapshotAdapter.php
  src/Snapshot/Adapter/Psr16SnapshotAdapter.php
  src/Snapshot/Adapter/Psr6SnapshotAdapter.php
  src/Snapshot/Adapter/SnapshotAdapter.php
  src/Snapshot/Adapter/SnapshotNotFound.php
  src/Snapshot/BatchSnapshotStore.php
  src/Snapshot/DefaultSnapshotStore.php
  src/Snapshot/InMemorySnapshotStore.php
  src/Snapshot/Psr16SnapshotStore.php
  src/Snapshot/Psr6SnapshotStore.php
  src/Snapshot/Snapshot.php
  src/Snapshot/SnapshotException.php
  src/Snapshot/SnapshotNotConfigured.php
  src/Snapshot/SnapshotNotFound.php
  src/Snapshot/SnapshotStore.php
  tests/Benchmark/BasicImplementation/Aggregate/Profile.php
  tests/Benchmark/LoadEventsWithSnapshotsBench.php
  tests/Integration/BasicImplementation/Aggregate/Profile.php
  tests/Integration/BasicImplementation/BasicIntegrationTest.php
  tests/Unit/Fixture/ProfileInvalid.php
  tests/Unit/Fixture/ProfileWithBrokenApplyBothUsage.php
  tests/Unit/Fixture/ProfileWithBrokenApplyIntersection.php
  tests/Unit/Fixture/ProfileWithBrokenApplyMultipleApply.php
  tests/Unit/Fixture/ProfileWithBrokenApplyNoType.php
  tests/Unit/Fixture/ProfileWithEmptyApply.php
  tests/Unit/Fixture/ProfileWithSnapshot.php
  tests/Unit/Fixture/ProfileWithSuppressAll.php
  tests/Unit/Repository/DefaultRepositoryTest.php
  tests/Unit/Repository/SnapshotRepositoryTest.php
  tests/Unit/Snapshot/Adapter/InMemorySnapshotAdapterTest.php
  tests/Unit/Snapshot/Adapter/Psr16SnapshotAdapterTest.php
  tests/Unit/Snapshot/Adapter/Psr6SnapshotAdapterTest.php
  tests/Unit/Snapshot/DefaultSnapshotStoreTest.php
  tests/Unit/Snapshot/InMemorySnapshotStoreTest.php
  tests/Unit/Snapshot/Psr16SnapshotStoreTest.php
  tests/Unit/Snapshot/Psr6SnapshotStoreTest.php
Labels: enhancement, BC-Break

#229 Rename FieldName to SerializedName
  src/Attribute/SerializedName.php
  src/Metadata/Event/AttributeEventMetadataFactory.php
  tests/Unit/Metadata/Event/AttributeEventMetadataFactoryTest.php
Labels: enhancement

#235 add repository manager
  src/Repository/DefaultRepository.php
  src/Repository/DefaultRepositoryManager.php
  src/Repository/Repository.php
  src/Repository/RepositoryManager.php
  tests/Unit/Repository/DefaultRepositoryManagerTest.php
  tests/Unit/Repository/DefaultRepositoryTest.php
Labels: enhancement

#238 Update infection for 2.0.x branch
  README.md
  infection.json.dist
Labels: documentation
