Repository patchlevel/event-sourcing, pull requests merged in 2022-01, with the labels that each got.

#155 snapshot after x events
  composer.json
  docs/snapshots.md
  infection.json.dist
  src/Snapshot/BatchSnapshotStore.php
  tests/Unit/Snapshot/BatchSnapshotStoreTest.php
  tests/Unit/Snapshot/InMemorySnapshotStoreTest.php
  tests/Unit/Snapshot/Psr16SnapshotStoreTest.php
  tests/Unit/Snapshot/Psr6SnapshotStoreTest.php
  tests/Unit/Snapshot/SnapshotTest.php
Labels: enhancement

#157 Update projection.md
  docs/projection.md
Labels: documentation

#158 add attribute based apply methods
  docs/aggregate.md
  phpstan-baseline.neon
  phpstan.neon.dist
  src/Aggregate/ApplyAttributeNotFound.php
  src/Aggregate/AttributeApplyMethod.php
  src/Aggregate/DuplicateApplyMethod.php
  src/Attribute/Apply.php
  src/Attribute/SuppressMissingApply.php
  tests/Unit/Aggregate/AggregateRootWithAttributeApplyTest.php
  tests/Unit/Attribute/SuppressMissingApplyTest.php
  tests/Unit/Fixture/MessageDeleted.php
  tests/Unit/Fixture/ProfileWithAttributeApply.php
  tests/Unit/Fixture/ProfileWithAttributeApplyInvalid.php
  tests/Unit/Fixture/ProfileWithAttributeApplySuppressAll.php
Labels: enhancement

#162 Update all unit-test with @covers annotation, add custom recordedOn test for AggregateChanged, use assertSame where possible, update infection config & badge
  README.md
  infection.json.dist
  phpunit.xml.dist
  tests/Integration/BasicImplementation/BasicIntegrationTest.php
  tests/Integration/Pipeline/PipelineChangeStoreTest.php
  tests/Unit/Aggregate/AggregateChangedTest.php
  tests/Unit/Aggregate/AggregateChangedWithClockTest.php
  tests/Unit/Aggregate/AggregateRootTest.php
  tests/Unit/Aggregate/AggregateRootWithAttributeApplyTest.php
  tests/Unit/Aggregate/AggregateRootWithNonStrictApplyTest.php
  tests/Unit/Aggregate/AggregateRootWithStrictApplyTest.php
  tests/Unit/Aggregate/SnapshotableAggregateRootTest.php
  tests/Unit/Attribute/SuppressMissingApplyTest.php
  tests/Unit/ClockTest.php
  tests/Unit/Console/Command/DatabaseCreateCommandTest.php
  tests/Unit/Console/Command/DatabaseDropCommandTest.php
  tests/Unit/Console/Command/ProjectionCreateCommandTest.php
  tests/Unit/Console/Command/ProjectionDropCommandTest.php
  tests/Unit/Console/Command/ProjectionRebuildCommandTest.php
  tests/Unit/Console/Command/SchemaCreateCommandTest.php
  tests/Unit/Console/Command/SchemaDropCommandTest.php
  tests/Unit/Console/Command/SchemaUpdateCommandTest.php
  tests/Unit/Console/Command/ShowCommandTest.php
  tests/Unit/Console/Command/WatchCommandTest.php
  tests/Unit/Console/DoctrineHelperTest.php
  tests/Unit/Console/EventPrinterTest.php
  tests/Unit/Console/InputHelperTest.php
  tests/Unit/Console/InvalidArgumentGivenTest.php
  tests/Unit/EventBus/DefaultEventBusTest.php
  tests/Unit/EventBus/SymfonyEventBusTest.php
  tests/Unit/Fixture/ProfileCreatedWithCustomRecordedOn.php
  tests/Unit/Pipeline/Middleware/ClassRenameMiddlewareTest.php
  tests/Unit/Pipeline/Middleware/ExcludeEventMiddlewareTest.php
  tests/Unit/Pipeline/Middleware/FilterEventMiddlewareTest.php
  tests/Unit/Pipeline/Middleware/FromIndexEventMiddlewareTest.php
  tests/Unit/Pipeline/Middleware/IncludeEventMiddlewareTest.php
  tests/Unit/Pipeline/Middleware/RecalculatePlayheadMiddlewareTest.php
  tests/Unit/Pipeline/Middleware/ReplaceEventMiddlewareTest.php
  tests/Unit/Pipeline/Middleware/UntilEventMiddlewareTest.php
  tests/Unit/Pipeline/PipelineTest.php
  tests/Unit/Pipeline/Target/InMemoryTargetTest.php
  tests/Unit/Pipeline/Target/ProjectionRepositoryTargetTest.php
  tests/Unit/Pipeline/Target/ProjectionTargetTest.php
  tests/Unit/Pipeline/Target/StoreTargetTest.php
  tests/Unit/Projection/AttributeHandleMethodTest.php
  tests/Unit/Projection/DefaultProjectionRepositoryTest.php
  tests/Unit/Projection/ProjectionListenerTest.php
  tests/Unit/Repository/DefaultRepositoryTest.php
  tests/Unit/Repository/SnapshotRepositoryTest.php
  tests/Unit/Schema/DoctrineSchemaManagerTest.php
  tests/Unit/Schema/MigrationSchemaProviderTest.php
  tests/Unit/Snapshot/BatchSnapshotStoreTest.php
  tests/Unit/Snapshot/InMemorySnapshotStoreTest.php
  tests/Unit/Snapshot/Psr16SnapshotStoreTest.php
  tests/Unit/Snapshot/Psr6SnapshotStoreTest.php
  tests/Unit/Snapshot/SnapshotTest.php
  tests/Unit/Store/SingleTableStoreTest.php
  tests/Unit/WatchServer/WatchListenerTest.php
Labels: enhancement

#163 Update analysers (pslam, phpstan & infection)
  .github/workflows/backward-compatibility-check.yml
  composer.json
  composer.lock
  infection.json.dist
Labels: dependencies

#164 add roave/infection-static-analysis-plugin
  .github/workflows/mutation-tests.yml
  composer.json
  composer.lock
Labels: enhancement

#176 update phpstan & psalm
  composer.json
  composer.lock
Labels: dependencies, php
