Repository patchlevel/event-sourcing, pull requests merged in 2022-07, with the labels that each got.

#288 require symfony console and remove deprecation
  composer.json
  composer.lock
  docs/pages/cli.md
  src/Console/Command/DatabaseCreateCommand.php
  src/Console/Command/DatabaseDropCommand.php
  src/Console/Command/DebugCommand.php
  src/Console/Command/OutboxConsumeCommand.php
  src/Console/Command/OutboxInfoCommand.php
  src/Console/Command/ProjectionCreateCommand.php
  src/Console/Command/ProjectionDropCommand.php
  src/Console/Command/ProjectionRebuildCommand.php
  src/Console/Command/SchemaCreateCommand.php
  src/Console/Command/SchemaDropCommand.php
  src/Console/Command/SchemaUpdateCommand.php
  src/Console/Command/ShowCommand.php
  src/Console/Command/WatchCommand.php
Labels: enhancement

#291 snapshots version
  baseline.xml
  docs/pages/snapshots.md
  phpstan-baseline.neon
  src/Attribute/Snapshot.php
  src/Metadata/AggregateRoot/AggregateRootMetadata.php
  src/Metadata/AggregateRoot/AttributeAggregateRootMetadataFactory.php
  src/Repository/DefaultRepository.php
  src/Snapshot/DefaultSnapshotStore.php
  src/Snapshot/SnapshotVersionInvalid.php
  tests/Unit/Fixture/ProfileWithSnapshot.php
  tests/Unit/Snapshot/DefaultSnapshotStoreTest.php
Labels: enhancement

#296 fix constructor typos in docs
  docs/pages/repository.md
  docs/pages/uuid.md
Labels: documentation

#299 Fix problem with database names using hyphens
  src/Console/DoctrineHelper.php
  tests/Unit/Console/DoctrineHelperTest.php
Labels: bug
