Repository patchlevel/event-sourcing, pull requests merged in 2024-02, with the labels that each got.

#479 Fix tests for dbal 3.8.x
  composer.json
  composer.lock
  tests/Unit/Store/MultiTableStoreTest.php
  tests/Unit/Store/SingleTableStoreTest.php
Labels: dependencies

#472 use array as trace in projection error
  phpstan-baseline.neon
  src/Console/Command/ProjectionStatusCommand.php
  src/Projection/Projection/Store/ErrorContext.php
Labels: enhancement

#480 fix worker commands
  composer.json
  composer.lock
  src/Console/Command/OutboxConsumeCommand.php
  src/Console/Command/ProjectionRunCommand.php
Labels: bug

#440 improve readme, index and getting started docs
  README.md
  docs/pages/getting_started.md
  docs/pages/index.md
Labels: documentation

#483 improve aggregate, clock, event bus and message decorator docs
  docs/mkdocs.yml
  docs/pages/aggregate.md
  docs/pages/aggregate_id.md
  docs/pages/clock.md
  docs/pages/event_bus.md
  docs/pages/events.md
  docs/pages/getting_started.md
  docs/pages/message_decorator.md
  docs/pages/testing.md
Labels: documentation

#485 improve projection errors and traces
  phpstan-baseline.neon
  phpunit.xml.dist
  src/Projection/Projection/Store/ErrorContext.php
  tests/Unit/Projection/Projection/ErrorContextTest.php
Labels: bug, enhancement

#486 remove apply implementation for aggregate root behaviour
  src/Aggregate/AggregateRootBehaviour.php
Labels: enhancement

#437 support dbal 4
  .github/workflows/integration.yml
  composer.json
  composer.lock
  phpstan-baseline.neon
  phpunit.xml.dist
  src/Outbox/DoctrineOutboxStore.php
  src/Projection/Projection/Store/DoctrineStore.php
  src/Store/DoctrineDbalStore.php
  tests/Integration/BankAccountSplitStream/IntegrationTest.php
  tests/Integration/BankAccountSplitStream/Projection/BankAccountProjector.php
  tests/Integration/BasicImplementation/BasicIntegrationTest.php
  tests/Integration/BasicImplementation/Projection/ProfileProjector.php
  tests/Integration/DbalManager.php
  tests/Integration/Outbox/OutboxTest.php
  tests/Integration/Outbox/Projection/ProfileProjector.php
  tests/Integration/Projectionist/Projection/ProfileProjector.php
  tests/Integration/Projectionist/ProjectionistTest.php
  tests/Unit/Schema/DoctrineSchemaDirectorTest.php
  tests/Unit/Store/DoctrineDbalStoreTest.php
Labels: enhancement

#487 use aggregate name in message to decouple components
  baseline.xml
  phpstan-baseline.neon
  src/Console/OutputStyle.php
  src/EventBus/HeaderNotFound.php
  src/EventBus/Message.php
  src/Outbox/DoctrineOutboxStore.php
  src/Pipeline/Middleware/RecalculatePlayheadMiddleware.php
  src/Repository/DefaultRepository.php
  src/Store/ArchivableStore.php
  src/Store/Criteria.php
  src/Store/CriteriaBuilder.php
  src/Store/DoctrineDbalStore.php
  src/Store/DoctrineDbalStoreStream.php
  tests/Benchmark/SimpleSetupBench.php
  tests/Benchmark/SnapshotsBench.php
  tests/Benchmark/SplitStreamBench.php
  tests/Benchmark/SyncProjectionistBench.php
  tests/Benchmark/blackfire.php
  tests/Integration/BankAccountSplitStream/IntegrationTest.php
  tests/Integration/BasicImplementation/BasicIntegrationTest.php
  tests/Integration/Outbox/OutboxTest.php
  tests/Integration/Pipeline/PipelineChangeStoreTest.php
  tests/Integration/Projectionist/ProjectionistTest.php
  tests/Integration/Store/StoreTest.php
  tests/Unit/Console/Command/OutboxInfoCommandTest.php
  tests/Unit/Console/Command/ShowAggregateCommandTest.php
  tests/Unit/Console/OutputStyleTest.php
  tests/Unit/EventBus/HeaderNotFoundTest.php
  tests/Unit/EventBus/MessageTest.php
  tests/Unit/Outbox/DoctrineOutboxStoreTest.php
  tests/Unit/Pipeline/Middleware/RecalculatePlayheadMiddlewareTest.php
  tests/Unit/Pipeline/PipelineTest.php
  tests/Unit/Repository/DefaultRepositoryTest.php
  tests/Unit/Store/DoctrineDbalStoreTest.php
Labels: enhancement, BC-Break

#491 extract consumer logic and rename outbox consumer into processor
  docs/pages/event_bus.md
  docs/pages/outbox.md
  src/Console/Command/OutboxConsumeCommand.php
  src/EventBus/Consumer.php
  src/EventBus/DefaultConsumer.php
  src/EventBus/DefaultEventBus.php
  src/Outbox/EventBusPublisher.php
  src/Outbox/OutboxConsumer.php
  src/Outbox/OutboxEventBus.php
  src/Outbox/OutboxProcessor.php
  src/Outbox/StoreOutboxProcessor.php
  tests/Integration/Outbox/OutboxTest.php
  tests/Unit/Console/Command/OutboxConsumeCommandTest.php
  tests/Unit/EventBus/DefaultConsumerTest.php
  tests/Unit/EventBus/DefaultEventBusTest.php
  tests/Unit/Outbox/EventBusPublisherTest.php
  tests/Unit/Outbox/StoreOutboxConsumerTest.php
Labels: enhancement, BC-Break

#492 add chain event bus and rewrite projectionist event bus
  docs/pages/event_bus.md
  docs/pages/getting_started.md
  src/EventBus/ChainEventBus.php
  src/Projection/Projectionist/ProjectionistEventBus.php
  tests/Benchmark/SyncProjectionistBench.php
  tests/Integration/BankAccountSplitStream/IntegrationTest.php
  tests/Integration/BasicImplementation/BasicIntegrationTest.php
  tests/Integration/Outbox/OutboxTest.php
  tests/Integration/Projectionist/ProjectionistTest.php
  tests/Unit/EventBus/ChainEventBusTest.php
  tests/Unit/Projection/Projectionist/ProjectionistEventBusTest.php
Labels: enhancement

#493 Update OutboxStore schema, extract MessageSerializer from WatchServer
  baseline.xml
  phpunit.xml.dist
  src/Console/InvalidArgumentGiven.php
  src/Console/OutputStyle.php
  src/EventBus/Serializer/DeserializeFailed.php
  src/EventBus/Serializer/EventSerializerMessageSerializer.php
  src/EventBus/Serializer/MessageSerializer.php
  src/EventBus/Serializer/PhpNativeMessageSerializer.php
  src/Outbox/DoctrineOutboxStore.php
  src/Outbox/OutboxHeaderIssue.php
  src/WatchServer/PhpNativeMessageSerializer.php
  src/WatchServer/SocketWatchServer.php
  src/WatchServer/SocketWatchServerClient.php
  src/WatchServer/WatchEventBus.php
  src/WatchServer/WatchListener.php
  tests/Integration/Outbox/OutboxTest.php
  tests/Unit/Console/InputHelperTest.php
  tests/Unit/Console/OutputStyleTest.php
  tests/Unit/EventBus/Serializer/EventSerializerMessageSerializerTest.php
  tests/Unit/EventBus/Serializer/PhpNativeMessageSerializerTest.php
  tests/Unit/Outbox/DoctrineOutboxStoreTest.php
  tests/Unit/WatchServer/PhpNativeMessageSerializerTest.php
  tests/Unit/WatchServer/WatchEventBusTest.php
Labels: enhancement, BC-Break

#494 Update Message with headers
  baseline.xml
  docs/pages/event_bus.md
  docs/pages/message_decorator.md
  phpstan-baseline.neon
  src/EventBus/Decorator/SplitStreamDecorator.php
  src/EventBus/HeaderNotFound.php
  src/EventBus/Message.php
  src/Outbox/DoctrineOutboxStore.php
  src/Pipeline/Middleware/ExcludeArchivedEventMiddleware.php
  src/Pipeline/Middleware/OnlyArchivedEventMiddleware.php
  src/Repository/DefaultRepository.php
  src/Store/DoctrineDbalStore.php
  src/Store/DoctrineDbalStoreStream.php
  src/Store/DoctrineHelper.php
  tests/Integration/BasicImplementation/MessageDecorator/FooMessageDecorator.php
  tests/Integration/Store/StoreTest.php
  tests/Unit/Aggregate/AggregateRootTest.php
  tests/Unit/EventBus/Decorator/SplitStreamDecoratorTest.php
  tests/Unit/EventBus/DefaultEventBusTest.php
  tests/Unit/EventBus/HeaderNotFoundTest.php
  tests/Unit/EventBus/MessageTest.php
  tests/Unit/EventBus/Serializer/DeserializeFailedTest.php
  tests/Unit/EventBus/Serializer/EventSerializerMessageSerializerTest.php
  tests/Unit/EventBus/Serializer/PhpNativeMessageSerializerTest.php
  tests/Unit/Outbox/DoctrineOutboxStoreTest.php
  tests/Unit/Outbox/OutboxHeaderIssueTest.php
  tests/Unit/Pipeline/Middleware/ExcludeArchivedEventMiddlewareTest.php
  tests/Unit/Pipeline/Middleware/OnlyArchivedEventMiddlewareTest.php
  tests/Unit/Repository/DefaultRepositoryTest.php
  tests/Unit/Serializer/SerializedEventTest.php
  tests/Unit/Store/ArrayStreamTest.php
  tests/Unit/Store/DoctrineDbalStoreTest.php
Labels: enhancement, BC-Break

#498 allow "subscribe all" in projectors
  baseline.xml
  src/Metadata/Projector/AttributeProjectorMetadataFactory.php
  src/Metadata/Projector/DuplicateSubscribeMethod.php
  src/Metadata/Projector/ProjectorMetadata.php
  src/Metadata/Projector/SubscribeAllNotSupported.php
  src/Pipeline/Target/ProjectorRepositoryTarget.php
  src/Pipeline/Target/ProjectorTarget.php
  src/Projection/Projectionist/DefaultProjectionist.php
  src/Projection/Projector/MetadataProjectorResolver.php
  src/Projection/Projector/ProjectorResolver.php
  tests/Unit/Metadata/Projector/AttributeProjectorMetadataFactoryTest.php
  tests/Unit/Pipeline/Target/ProjectorRepositoryTargetTest.php
  tests/Unit/Pipeline/Target/ProjectorTargetTest.php
  tests/Unit/Projection/Projectionist/DefaultProjectionistTest.php
  tests/Unit/Projection/Projector/MetadataProjectorResolverTest.php
Labels: enhancement, BC-Break

#499 add consumer target and replace old projector targets
  docs/pages/pipeline.md
  src/Pipeline/Target/ConsumerTarget.php
  src/Pipeline/Target/ProjectorRepositoryTarget.php
  src/Pipeline/Target/ProjectorTarget.php
  tests/Unit/Pipeline/Target/ConsumerTargetTest.php
  tests/Unit/Pipeline/Target/ProjectorRepositoryTargetTest.php
  tests/Unit/Pipeline/Target/ProjectorTargetTest.php
Labels: enhancement, BC-Break

#501 remove sync projectionist
  composer.json
  composer.lock
  docs/pages/getting_started.md
  src/Lock/DoctrineDbalStoreSchemaAdapter.php
  src/Projection/Projectionist/ProjectionistEventBus.php
  tests/Benchmark/SyncProjectionistBench.php
  tests/Integration/BankAccountSplitStream/IntegrationTest.php
  tests/Integration/BasicImplementation/BasicIntegrationTest.php
  tests/Integration/Outbox/OutboxTest.php
  tests/Integration/Projectionist/ProjectionistTest.php
  tests/Unit/Lock/DoctrineDbalStoreSchemaAdapterTest.php
  tests/Unit/Projection/Projectionist/ProjectionistEventBusTest.php
Labels: BC-Break

#502 move message decorator into repository
  docs/pages/message_decorator.md
  src/Repository/DefaultRepository.php
  src/Repository/DefaultRepositoryManager.php
  src/Repository/MessageDecorator/ChainMessageDecorator.php
  src/Repository/MessageDecorator/MessageDecorator.php
  src/Repository/MessageDecorator/SplitStreamDecorator.php
  tests/Benchmark/SplitStreamBench.php
  tests/Integration/BankAccountSplitStream/IntegrationTest.php
  tests/Integration/BasicImplementation/MessageDecorator/FooMessageDecorator.php
  tests/Unit/Repository/DefaultRepositoryTest.php
  tests/Unit/Repository/MessageDecorator/ChainMessageDecoratorTest.php
  tests/Unit/Repository/MessageDecorator/SplitStreamDecoratorTest.php
Labels: BC-Break

#500 "from now" mode for projections
  baseline.xml
  docs/pages/projection.md
  phpstan-baseline.neon
  src/Attribute/Projector.php
  src/Metadata/Projector/AttributeProjectorMetadataFactory.php
  src/Metadata/Projector/ProjectorMetadata.php
  src/Projection/Projectionist/DefaultProjectionist.php
  src/Projection/Projector/InMemoryProjectorRepository.php
  src/Projection/Projector/MetadataProjectorResolver.php
  src/Projection/Projector/ProjectorRepository.php
  src/Projection/Projector/ProjectorResolver.php
  tests/Integration/BankAccountSplitStream/IntegrationTest.php
  tests/Integration/BasicImplementation/BasicIntegrationTest.php
  tests/Integration/Projectionist/ProjectionistTest.php
  tests/Unit/Projection/Projectionist/DefaultProjectionistTest.php
  tests/Unit/Projection/Projector/InMemoryProjectorRepositoryTest.php
  tests/Unit/Projection/Projector/MetadataProjectorResolverTest.php
Labels: enhancement, BC-Break

#503 overhaul projectionist
  baseline.xml
  docs/pages/getting_started.md
  docs/pages/projection.md
  src/Attribute/Projector.php
  src/Console/Command/ProjectionCommand.php
  src/Console/Command/ProjectionStatusCommand.php
  src/Console/InputHelper.php
  src/Metadata/Projector/AttributeProjectorMetadataFactory.php
  src/Metadata/Projector/ProjectorMetadata.php
  src/Projection/Projection/DuplicateProjectionId.php
  src/Projection/Projection/Projection.php
  src/Projection/Projection/ProjectionAlreadyExists.php
  src/Projection/Projection/ProjectionCollection.php
  src/Projection/Projection/ProjectionCriteria.php
  src/Projection/Projection/ProjectionStatus.php
  src/Projection/Projection/RunMode.php
  src/Projection/Projection/Store/DoctrineStore.php
  src/Projection/Projection/Store/InMemoryStore.php
  src/Projection/Projection/Store/LockableProjectionStore.php
  src/Projection/Projection/Store/ProjectionStore.php
  src/Projection/Projection/Store/TransactionCommitNotPossible.php
  src/Projection/Projectionist/DefaultProjectionist.php
  src/Projection/Projectionist/Projectionist.php
  src/Projection/Projectionist/ProjectionistCriteria.php
  tests/Integration/BankAccountSplitStream/IntegrationTest.php
  tests/Integration/BasicImplementation/BasicIntegrationTest.php
  tests/Integration/Projectionist/ProjectionistTest.php
  tests/Unit/Projection/DummyStore.php
  tests/Unit/Projection/Projection/DuplicateProjectionIdTest.php
  tests/Unit/Projection/Projection/ProjectionAlreadyExistsTest.php
  tests/Unit/Projection/Projection/ProjectionCollectionTest.php
  tests/Unit/Projection/Projection/ProjectionCriteriaTest.php
  tests/Unit/Projection/Projection/Store/InMemoryStoreTest.php
  tests/Unit/Projection/Projectionist/DefaultProjectionistTest.php
Labels: enhancement, BC-Break

#505 remove optional dependency and add required doctrine migration
  composer.json
  composer.lock
  docs/mkdocs.yml
  docs/pages/cli.md
  docs/pages/migration.md
  docs/pages/store.md
  src/Store/DoctrineDbalStore.php
Labels: enhancement

#504 overhaul error handling in projectionist
  baseline.xml
  docs/pages/projection.md
  phpstan-baseline.neon
  src/Console/Command/ProjectionBootCommand.php
  src/Console/Command/ProjectionRebuildCommand.php
  src/Console/Command/ProjectionRunCommand.php
  src/Console/Command/ProjectionStatusCommand.php
  src/Projection/Projection/NoErrorToRetry.php
  src/Projection/Projection/Projection.php
  src/Projection/Projection/ProjectionError.php
  src/Projection/Projection/Store/DoctrineStore.php
  src/Projection/Projection/ThrowableToErrorContextTransformer.php
  src/Projection/Projectionist/DefaultProjectionist.php
  src/Projection/Projectionist/Projectionist.php
  src/Projection/Projectionist/ProjectionistError.php
  src/Projection/RetryStrategy/ClockBasedRetryStrategy.php
  src/Projection/RetryStrategy/NoRetryStrategy.php
  src/Projection/RetryStrategy/RetryStrategy.php
  src/Projection/RetryStrategy/UnexpectedError.php
  tests/Integration/BankAccountSplitStream/IntegrationTest.php
  tests/Integration/BasicImplementation/BasicIntegrationTest.php
  tests/Integration/Projectionist/Projection/ErrorProducerProjector.php
  tests/Integration/Projectionist/ProjectionistTest.php
  tests/Unit/Projection/Projection/ErrorContextTest.php
  tests/Unit/Projection/Projection/ProjectionErrorTest.php
  tests/Unit/Projection/Projection/ProjectionTest.php
  tests/Unit/Projection/Projection/Store/ErrorContextTest.php
  tests/Unit/Projection/Projectionist/DefaultProjectionistTest.php
  tests/Unit/Projection/RetryStrategy/ClockBasedRetryStrategyTest.php
  tests/Unit/Projection/RetryStrategy/NoRetryStrategyTest.php
Labels: enhancement, BC-Break

#508 remove watch server & use event store for watching
  README.md
  docs/mkdocs.yml
  docs/pages/cli.md
  docs/pages/index.md
  docs/pages/watch_server.md
  phpstan-baseline.neon
  src/Console/Command/WatchCommand.php
  src/WatchServer/SendingFailed.php
  src/WatchServer/SocketWatchServer.php
  src/WatchServer/SocketWatchServerClient.php
  src/WatchServer/WatchEventBus.php
  src/WatchServer/WatchServer.php
  src/WatchServer/WatchServerClient.php
  tests/Unit/Console/Command/WatchCommandTest.php
  tests/Unit/WatchServer/WatchEventBusTest.php
Labels: enhancement, BC-Break

#510 upgrade hydrator & use new auto detect feature
  composer.json
  composer.lock
  docs/pages/aggregate.md
  docs/pages/aggregate_id.md
  docs/pages/events.md
  docs/pages/getting_started.md
  docs/pages/normalizer.md
  docs/pages/split_stream.md
  src/Serializer/Normalizer/IdNormalizer.php
  tests/Benchmark/BasicImplementation/Aggregate/Profile.php
  tests/Benchmark/BasicImplementation/Events/ProfileCreated.php
  tests/Benchmark/BasicImplementation/Events/Reborn.php
  tests/Integration/BankAccountSplitStream/Events/BalanceAdded.php
  tests/Integration/BankAccountSplitStream/Events/BankAccountCreated.php
  tests/Integration/BankAccountSplitStream/Events/MonthPassed.php
  tests/Integration/BankAccountSplitStream/Normalizer/AccountIdNormalizer.php
  tests/Integration/BasicImplementation/Aggregate/Profile.php
  tests/Integration/BasicImplementation/Events/ProfileCreated.php
  tests/Integration/BasicImplementation/Normalizer/ProfileIdNormalizer.php
  tests/Integration/Outbox/Aggregate/Profile.php
  tests/Integration/Outbox/Events/ProfileCreated.php
  tests/Integration/Outbox/Normalizer/ProfileIdNormalizer.php
  tests/Integration/Projectionist/Aggregate/Profile.php
  tests/Integration/Projectionist/Events/ProfileCreated.php
  tests/Integration/Projectionist/Normalizer/ProfileIdNormalizer.php
  tests/Integration/Store/Events/ProfileCreated.php
  tests/Integration/Store/Normalizer/ProfileIdNormalizer.php
  tests/Integration/Store/Profile.php
  tests/Unit/Fixture/ProfileCreated.php
  tests/Unit/Fixture/ProfileIdNormalizer.php
  tests/Unit/Fixture/ProfileVisited.php
  tests/Unit/Fixture/ProfileWithSnapshot.php
  tests/Unit/Serializer/Normalizer/IdNormalizerTest.php
Labels: enhancement

#511 allow to pause projections
  docs/pages/cli.md
  docs/pages/projection.md
  src/Console/Command/ProjectionPauseCommand.php
  src/Projection/Projection/Projection.php
  src/Projection/Projection/ProjectionStatus.php
  src/Projection/Projectionist/DefaultProjectionist.php
  src/Projection/Projectionist/Projectionist.php
  tests/Unit/Projection/Projectionist/DefaultProjectionistTest.php
Labels: enhancement, BC-Break

#512 fix start position of "from now" projections
  src/Projection/Projectionist/DefaultProjectionist.php
  tests/Unit/Projection/Projectionist/DefaultProjectionistTest.php
Labels: bug
