Repository patchlevel/event-sourcing, pull requests merged in 2024-12, with the labels that each got.

#650 add early out in subscription engine
  Makefile
  baseline.xml
  src/Subscription/Engine/DefaultSubscriptionEngine.php
  src/Subscription/Engine/SubscriptionCollection.php
  src/Subscription/Engine/SubscriptionManager.php
  tests/Unit/Subscription/Engine/SubscriptionCollectionTest.php
  tests/Unit/Subscription/Engine/SubscriptionManagerTest.php
Labels: enhancement

#653 dont lock for discoverNewSubscriptions & get subscriptions
  src/Subscription/Engine/DefaultSubscriptionEngine.php
  tests/Unit/Subscription/Engine/DefaultSubscriptionEngineTest.php
Labels: bug

#637 filter events in subscription engine
  deptrac.yaml
  docs/pages/our-backward-compatibility-promise.md
  docs/pages/store.md
  docs/pages/subscription.md
  src/Store/Criteria/CriteriaBuilder.php
  src/Store/Criteria/EventsCriterion.php
  src/Store/DoctrineDbalStore.php
  src/Store/StreamDoctrineDbalStore.php
  src/Subscription/Engine/DefaultSubscriptionEngine.php
  src/Subscription/Engine/EventFilteredStoreMessageLoader.php
  src/Subscription/Engine/MessageLoader.php
  src/Subscription/Engine/StoreMessageLoader.php
  src/Subscription/Engine/SubscriptionCollection.php
  src/Subscription/Subscriber/MetadataSubscriberAccessor.php
  tests/Benchmark/SubscriptionEngineBench.php
  tests/Integration/Subscription/SubscriptionTest.php
  tests/Unit/Store/Crtieria/CriteriaBuilderTest.php
Labels: enhancement

#656 [Experimental] split stream header into 3 separate headers
  baseline.xml
  phpstan-baseline.neon
  src/Console/OutputStyle.php
  src/Message/Translator/AggregateToStreamHeaderTranslator.php
  src/Message/Translator/RecalculatePlayheadTranslator.php
  src/Message/Translator/UntilEventTranslator.php
  src/Metadata/Message/MessageHeaderRegistry.php
  src/Repository/DefaultRepository.php
  src/Store/Header/PlayheadHeader.php
  src/Store/Header/RecordedOnHeader.php
  src/Store/Header/StreamNameHeader.php
  src/Store/InMemoryStore.php
  src/Store/StreamDoctrineDbalStore.php
  src/Store/StreamDoctrineDbalStoreStream.php
  src/Store/StreamHeader.php
  src/Subscription/Subscriber/ArgumentResolver/AggregateIdArgumentResolver.php
  tests/Integration/Store/StreamDoctrineDbalStoreTest.php
  tests/Unit/Message/Translator/AggregateToStreamHeaderTranslatorTest.php
  tests/Unit/Message/Translator/RecalculatePlayheadTranslatorTest.php
  tests/Unit/Store/InMemoryStoreTest.php
  tests/Unit/Store/StreamDoctrineDbalStoreTest.php
  tests/Unit/Store/StreamDoctrineDbalStreamTest.php
Labels: BC-Break

#657 [Experimental] introduce event id & fix split stream logic in stream store
  Makefile
  docker-compose.yaml
  src/Metadata/Message/MessageHeaderRegistry.php
  src/Store/Header/EventIdHeader.php
  src/Store/StreamDoctrineDbalStore.php
  src/Store/StreamDoctrineDbalStoreStream.php
  tests/Integration/Store/StreamDoctrineDbalStoreTest.php
  tests/Unit/Store/StreamDoctrineDbalStoreTest.php
  tests/Unit/Store/StreamDoctrineDbalStreamTest.php
Labels: enhancement

#658 Allow to configure stream name in aggregate
  deptrac-baseline.yaml
  docs/pages/aggregate.md
  src/Aggregate/AggregateHeader.php
  src/Aggregate/StreamNameTranslator.php
  src/Attribute/Stream.php
  src/Console/Command/ShowAggregateCommand.php
  src/Console/Command/WatchCommand.php
  src/Metadata/AggregateRoot/AggregateRootMetadata.php
  src/Metadata/AggregateRoot/AttributeAggregateRootMetadataFactory.php
  src/Metadata/AggregateRoot/MissingAggregateIdForStreamName.php
  src/Repository/DefaultRepository.php
  src/Subscription/Subscriber/ArgumentResolver/AggregateIdArgumentResolver.php
  tests/Integration/MicroAggregate/Events/NameChanged.php
  tests/Integration/MicroAggregate/Events/ProfileCreated.php
  tests/Integration/MicroAggregate/MicroAggregateIntegrationTest.php
  tests/Integration/MicroAggregate/PersonalInformation.php
  tests/Integration/MicroAggregate/Profile.php
  tests/Integration/MicroAggregate/ProfileId.php
  tests/Integration/MicroAggregate/Projection/ProfileProjector.php
  tests/Integration/MicroAggregate/SendEmailMock.php
  tests/Unit/Fixture/ProfileWithStream.php
  tests/Unit/Metadata/Aggregate/AttributeAggregateMetadataFactoryTest.php
  tests/Unit/Repository/DefaultRepositoryTest.php
Labels: enhancement

#661 add clear method in in memory store
  src/Subscription/Store/InMemorySubscriptionStore.php
  tests/Unit/Subscription/Store/InMemorySubscriptionStoreTest.php
Labels: enhancement

#662 only retry relevant subscriptions
  src/Subscription/Engine/DefaultSubscriptionEngine.php
  tests/Unit/Subscription/Engine/DefaultSubscriptionEngineTest.php
Labels: bug

#664 Failed status
  docs/pages/subscription.md
  src/Subscription/Engine/DefaultSubscriptionEngine.php
  src/Subscription/RetryStrategy/ClockBasedRetryStrategy.php
  src/Subscription/RetryStrategy/ConditionalRetryStrategy.php
  src/Subscription/RetryStrategy/NoRetryStrategy.php
  src/Subscription/Status.php
  src/Subscription/Subscription.php
  tests/Integration/Subscription/SubscriptionTest.php
  tests/Unit/Subscription/Engine/DefaultSubscriptionEngineTest.php
Labels: enhancement

#665 Fix ChainTranslator: Dont override the result keys, merge instead
  src/Message/Translator/ChainTranslator.php
  tests/Unit/Message/Translator/ChainTranslatorTest.php
Labels: bug
