Repository patchlevel/event-sourcing, pull requests merged in 2024-03, with the labels that each got.

#517 improve batch processing in projectionist
  src/Projection/Projectionist/DefaultProjectionist.php
  tests/Unit/Projection/Projectionist/DefaultProjectionistTest.php
Labels: enhancement

#519 save 10000 events
  src/Store/DoctrineDbalStore.php
  tests/Integration/Store/StoreTest.php
Labels: bug

#520 rename schema configurator into doctrine schema configurator
  docs/pages/getting_started.md
  docs/pages/projection.md
  src/Outbox/DoctrineOutboxStore.php
  src/Projection/Projection/Store/DoctrineStore.php
  src/Schema/ChainDoctrineSchemaConfigurator.php
  src/Schema/DoctrineSchemaConfigurator.php
  src/Schema/DoctrineSchemaDirector.php
  src/Schema/DoctrineSchemaSubscriber.php
  src/Store/DoctrineDbalStore.php
  tests/Benchmark/ProjectionistBench.php
  tests/Integration/Outbox/OutboxTest.php
  tests/Integration/Projectionist/ProjectionistTest.php
  tests/Unit/Schema/ChainDoctrineSchemaConfiguratorTest.php
  tests/Unit/Schema/DoctrineSchemaDirectorTest.php
  tests/Unit/Schema/DoctrineSchemaSubscriberTest.php
Labels: BC-Break

#522 fix watch command
  src/Console/Command/WatchCommand.php
Labels: bug

#514 projector accessor & experimental trace feature
  Makefile
  baseline.xml
  docs/pages/getting_started.md
  docs/pages/projection.md
  src/Projection/Projectionist/DefaultProjectionist.php
  src/Projection/Projector/MetadataProjectorAccessor.php
  src/Projection/Projector/MetadataProjectorAccessorRepository.php
  src/Projection/Projector/ProjectorAccessor.php
  src/Projection/Projector/ProjectorAccessorRepository.php
  src/Projection/Projector/TraceableProjectorAccessor.php
  src/Projection/Projector/TraceableProjectorAccessorRepository.php
  src/Repository/MessageDecorator/Trace.php
  src/Repository/MessageDecorator/TraceDecorator.php
  src/Repository/MessageDecorator/TraceHeader.php
  src/Repository/MessageDecorator/TraceStack.php
  tests/Benchmark/ProjectionistBench.php
  tests/Integration/BankAccountSplitStream/IntegrationTest.php
  tests/Integration/BasicImplementation/BasicIntegrationTest.php
  tests/Integration/Projectionist/Aggregate/Profile.php
  tests/Integration/Projectionist/Events/NameChanged.php
  tests/Integration/Projectionist/Projection/ProfileProcessor.php
  tests/Integration/Projectionist/ProjectionistTest.php
  tests/Unit/Projection/Projectionist/DefaultProjectionistTest.php
  tests/Unit/Projection/Projector/MetadataProjectorAccessorRepositoryTest.php
  tests/Unit/Projection/Projector/MetadataProjectorAccessorTest.php
  tests/Unit/Repository/MessageDecorator/TraceDecoratorTest.php
  tests/Unit/Repository/MessageDecorator/TraceStackTest.php
Labels: enhancement, BC-Break

#523 remove outbox store
  docs/pages/cli.md
  docs/pages/event_bus.md
  src/Console/Command/OutboxConsumeCommand.php
  src/Console/Command/OutboxInfoCommand.php
  src/EventBus/ChainEventBus.php
  src/EventBus/Serializer/EventSerializerMessageSerializer.php
  src/EventBus/Serializer/MessageSerializer.php
  src/EventBus/Serializer/PhpNativeMessageSerializer.php
  src/Outbox/DoctrineOutboxStore.php
  src/Outbox/EventBusPublisher.php
  src/Outbox/OutboxEventBus.php
  src/Outbox/OutboxHeader.php
  src/Outbox/OutboxHeaderIssue.php
  src/Outbox/OutboxProcessor.php
  src/Outbox/OutboxPublisher.php
  src/Outbox/OutboxStore.php
  src/Outbox/StoreOutboxProcessor.php
  tests/Integration/Outbox/Aggregate/Profile.php
  tests/Integration/Outbox/Events/ProfileCreated.php
  tests/Integration/Outbox/OutboxTest.php
  tests/Integration/Outbox/Processor/SendEmailProcessor.php
  tests/Integration/Outbox/ProfileId.php
  tests/Integration/Outbox/Projection/ProfileProjector.php
  tests/Integration/Outbox/SendEmailMock.php
  tests/Unit/Console/Command/OutboxConsumeCommandTest.php
  tests/Unit/Console/Command/OutboxInfoCommandTest.php
  tests/Unit/EventBus/ChainEventBusTest.php
  tests/Unit/EventBus/Serializer/EventSerializerMessageSerializerTest.php
  tests/Unit/EventBus/Serializer/PhpNativeMessageSerializerTest.php
  tests/Unit/Outbox/DoctrineOutboxStoreTest.php
  tests/Unit/Outbox/EventBusPublisherTest.php
  tests/Unit/Outbox/OutboxEventBusTest.php
  tests/Unit/Outbox/OutboxHeaderIssueTest.php
  tests/Unit/Outbox/OutboxHeaderTest.php
  tests/Unit/Outbox/StoreOutboxConsumerTest.php
Labels: BC-Break

#528 allow to free result after stream closed
  Makefile
  docker-compose.yaml
  src/Store/DoctrineDbalStoreStream.php
  src/Store/Stream.php
  src/Store/StreamClosed.php
  tests/Integration/Store/StoreTest.php
Labels: bug

#527 Fix customHeader method to actually check for the header existing
  src/EventBus/Message.php
  tests/Unit/EventBus/MessageTest.php
Labels: bug

#530 add projector and processor attributes
  docs/pages/getting_started.md
  docs/pages/subscription.md
  src/Attribute/Processor.php
  src/Attribute/Projector.php
  src/Attribute/Subscriber.php
  src/Metadata/Subscriber/AttributeSubscriberMetadataFactory.php
  tests/Benchmark/BasicImplementation/Processor/SendEmailProcessor.php
  tests/Benchmark/BasicImplementation/Projection/ProfileProjector.php
  tests/Integration/BankAccountSplitStream/Projection/BankAccountProjector.php
  tests/Integration/BasicImplementation/Projection/ProfileProjector.php
  tests/Integration/Subscription/Subscriber/ErrorProducerSubscriber.php
  tests/Integration/Subscription/Subscriber/ProfileProcessor.php
  tests/Integration/Subscription/Subscriber/ProfileProjection.php
  tests/Integration/Subscription/SubscriptionTest.php
  tests/Unit/Attribute/SubscriberTest.php
  tests/Unit/Fixture/Dummy2Subscriber.php
  tests/Unit/Fixture/DummySubscriber.php
  tests/Unit/Metadata/Subscriber/AttributeSubscriberMetadataFactoryTest.php
  tests/Unit/Subscription/Engine/DefaultSubscriptionEngineTest.php
  tests/Unit/Subscription/Subscriber/MetadataSubscriberAccessorRepositoryTest.php
  tests/Unit/Subscription/Subscriber/MetadataSubscriberAccessorTest.php
  tests/Unit/Subscription/Subscriber/SubscriberHelperTest.php
Labels: enhancement

#531 split boot method into boot and setup in subscription engine
  composer.json
  composer.lock
  docs/pages/cli.md
  docs/pages/getting_started.md
  docs/pages/subscription.md
  src/Console/Command/SubscriptionBootCommand.php
  src/Console/Command/SubscriptionSetupCommand.php
  src/Store/DoctrineDbalStore.php
  src/Subscription/Engine/DefaultSubscriptionEngine.php
  src/Subscription/Engine/SubscriptionEngine.php
  tests/Benchmark/SubscriptionEngineBench.php
  tests/Integration/BankAccountSplitStream/IntegrationTest.php
  tests/Integration/BasicImplementation/BasicIntegrationTest.php
  tests/Integration/Subscription/SubscriptionTest.php
  tests/Unit/Repository/DefaultRepositoryTest.php
  tests/Unit/Store/DoctrineDbalStoreTest.php
  tests/Unit/Subscription/Engine/DefaultSubscriptionEngineTest.php
Labels: enhancement, BC-Break

#538 move trace feature into debug namespace
  Makefile
  deptrac-baseline.yaml
  deptrac.yaml
  src/Debug/Trace/Trace.php
  src/Debug/Trace/TraceDecorator.php
  src/Debug/Trace/TraceHeader.php
  src/Debug/Trace/TraceStack.php
  src/Debug/Trace/TraceableSubscriberAccessor.php
  src/Debug/Trace/TraceableSubscriberAccessorRepository.php
  tests/Integration/Subscription/SubscriptionTest.php
  tests/Unit/Debug/Trace/TraceDecoratorTest.php
  tests/Unit/Debug/Trace/TraceStackTest.php
Labels: enhancement

#536 worker should not discover new subscriptions in running process
  src/Console/Command/SubscriptionBootCommand.php
  src/Console/Command/SubscriptionCommand.php
  src/Console/Command/SubscriptionRunCommand.php
  src/Subscription/Store/DoctrineSubscriptionStore.php
  tests/Integration/Subscription/Subscriber/ProfileNewProjection.php
  tests/Integration/Subscription/SubscriptionTest.php
Labels: enhancement

#544 Update deptrac to 2.0.0-alpha
  tools/composer.json
  tools/composer.lock
Labels: dependencies

#525 use for postgres pub/sub feature
  baseline.xml
  src/Console/Command/SubscriptionBootCommand.php
  src/Console/Command/SubscriptionRunCommand.php
  src/Console/Command/WatchCommand.php
  src/Store/DoctrineDbalStore.php
  src/Store/SubscriptionStore.php
Labels: enhancement

#548 docs: format & fix php errors
  .gitattributes
  .github/workflows/docs-check.yml
  .gitignore
  Makefile
  bin/docs-extract-php-code
  bin/docs-inject-php-code
  composer.json
  composer.lock
  docs/pages/aggregate.md
  docs/pages/aggregate_id.md
  docs/pages/cli.md
  docs/pages/clock.md
  docs/pages/event_bus.md
  docs/pages/events.md
  docs/pages/getting_started.md
  docs/pages/index.md
  docs/pages/message_decorator.md
  docs/pages/normalizer.md
  docs/pages/outbox.md
  docs/pages/pipeline.md
  docs/pages/repository.md
  docs/pages/snapshots.md
  docs/pages/split_stream.md
  docs/pages/store.md
  docs/pages/subscription.md
  docs/pages/testing.md
  docs/pages/upcasting.md
  psalm_docs.xml
Labels: documentation

#547 make the event bus optional
  docs/pages/getting_started.md
  docs/pages/repository.md
  src/Repository/DefaultRepository.php
  src/Repository/DefaultRepositoryManager.php
  tests/Benchmark/SimpleSetupBench.php
  tests/Benchmark/SnapshotsBench.php
  tests/Benchmark/SplitStreamBench.php
  tests/Benchmark/SubscriptionEngineBench.php
  tests/Benchmark/blackfire.php
  tests/Integration/BankAccountSplitStream/IntegrationTest.php
  tests/Integration/Pipeline/PipelineChangeStoreTest.php
  tests/Integration/Subscription/SubscriptionTest.php
  tests/Unit/Repository/DefaultRepositoryTest.php
Labels: enhancement, BC-Break

#550 fix some docs issues
  bin/docs-extract-php-code
  docs/pages/aggregate.md
  docs/pages/cli.md
  docs/pages/events.md
  docs/pages/getting_started.md
  docs/pages/message_decorator.md
  docs/pages/normalizer.md
  docs/pages/repository.md
  docs/pages/snapshots.md
  docs/pages/store.md
  docs/pages/subscription.md
  docs/pages/upcasting.md
  psalm_docs.xml
Labels: documentation

#549 Add infection on diff
  .github/workflows/mutation-tests-diff.yml
  composer.json
  composer.lock
Labels: enhancement

#541 load the internal header automatically
  deptrac.yaml
  src/Aggregate/AggregateHeader.php
  src/Debug/Trace/TraceHeader.php
  src/Message/Serializer/DefaultHeadersSerializer.php
  src/Metadata/Message/AttributeMessageHeaderRegistryFactory.php
  src/Metadata/Message/MessageHeaderRegistry.php
  src/Store/ArchivedHeader.php
  src/Store/DoctrineDbalStore.php
  src/Store/NewStreamStartHeader.php
  tests/Benchmark/SimpleSetupBench.php
  tests/Benchmark/SnapshotsBench.php
  tests/Benchmark/SplitStreamBench.php
  tests/Benchmark/SubscriptionEngineBench.php
  tests/Integration/BankAccountSplitStream/IntegrationTest.php
  tests/Integration/BasicImplementation/BasicIntegrationTest.php
  tests/Integration/Pipeline/PipelineChangeStoreTest.php
  tests/Integration/Store/StoreTest.php
  tests/Integration/Subscription/SubscriptionTest.php
  tests/Unit/Message/Serializer/HeadersSerializerTest.php
Labels: enhancement

#552 Argument resolver for subscriber
  baseline.xml
  deptrac.yaml
  src/Metadata/Subscriber/ArgumentMetadata.php
  src/Metadata/Subscriber/ArgumentTypeNotSupported.php
  src/Metadata/Subscriber/AttributeSubscriberMetadataFactory.php
  src/Metadata/Subscriber/SubscribeMethodMetadata.php
  src/Metadata/Subscriber/SubscriberMetadata.php
  src/Subscription/Subscriber/ArgumentResolver/AggregateIdArgumentResolver.php
  src/Subscription/Subscriber/ArgumentResolver/ArgumentResolver.php
  src/Subscription/Subscriber/ArgumentResolver/EventArgumentResolver.php
  src/Subscription/Subscriber/ArgumentResolver/MessageArgumentResolver.php
  src/Subscription/Subscriber/ArgumentResolver/RecordedOnArgumentResolver.php
  src/Subscription/Subscriber/MetadataSubscriberAccessor.php
  src/Subscription/Subscriber/MetadataSubscriberAccessorRepository.php
  src/Subscription/Subscriber/NoSuitableResolver.php
  tests/Benchmark/BasicImplementation/Projection/ProfileProjector.php
  tests/Integration/BasicImplementation/BasicIntegrationTest.php
  tests/Integration/BasicImplementation/Listener/SendEmailListener.php
  tests/Integration/BasicImplementation/Projection/ProfileProjector.php
  tests/Unit/Metadata/Subscriber/AttributeSubscriberMetadataFactoryTest.php
  tests/Unit/Subscription/Subscriber/ArgumentResolver/AggregateIdArgumentResolverTest.php
  tests/Unit/Subscription/Subscriber/ArgumentResolver/EventArgumentResolverTest.php
  tests/Unit/Subscription/Subscriber/ArgumentResolver/MessageArgumentResolverTest.php
  tests/Unit/Subscription/Subscriber/ArgumentResolver/RecordedOnArgumentResolverTest.php
  tests/Unit/Subscription/Subscriber/MetadataSubscriberAccessorRepositoryTest.php
  tests/Unit/Subscription/Subscriber/MetadataSubscriberAccessorTest.php
Labels: enhancement

#554 add skip booting flag into setup command
  src/Console/Command/SubscriptionSetupCommand.php
Labels: enhancement

#556 throw stream close exception in array stream implementation
  src/Store/ArrayStream.php
  src/Subscription/Engine/DefaultSubscriptionEngine.php
  tests/Unit/Store/ArrayStreamTest.php
  tests/Unit/Subscription/Engine/DefaultSubscriptionEngineTest.php
Labels: bug

#555 display group and run mode in subscription status command
  src/Console/Command/SubscriptionStatusCommand.php
Labels: enhancement

#557 fix notify trigger
  src/Store/DoctrineDbalStore.php
Labels: bug

#558 fix log output end of stream in subscription engine
  src/Subscription/Engine/DefaultSubscriptionEngine.php
Labels: bug
