Repository patchlevel/event-sourcing, pull requests merged in 2024-04, with the labels that each got.

#560 Add *Stream and DoctrineHelper tests
  baseline.xml
  infection.json.dist
  src/Store/ArrayStream.php
  src/Store/DoctrineDbalStoreStream.php
  tests/Unit/Store/DoctrineDbalStreamTest.php
  tests/Unit/Store/DoctrineHelperTest.php
Labels: enhancement

#564 Message docs
  docs/mkdocs.yml
  docs/pages/event_bus.md
  docs/pages/getting_started.md
  docs/pages/message.md
  docs/pages/pipeline.md
Labels: documentation

#565 remove nested encoding
  baseline.xml
  deptrac.yaml
  src/Console/OutputStyle.php
  src/Message/Serializer/DefaultHeadersSerializer.php
  src/Message/Serializer/DeserializeFailed.php
  src/Message/Serializer/HeadersSerializer.php
  src/Message/Serializer/InvalidArgument.php
  src/Store/DoctrineDbalStore.php
  src/Store/DoctrineDbalStoreStream.php
  src/Store/DoctrineHelper.php
  tests/Unit/Console/Command/ShowAggregateCommandTest.php
  tests/Unit/Console/OutputStyleTest.php
  tests/Unit/Message/Serializer/DefaultHeadersSerializerTest.php
  tests/Unit/Message/Serializer/DeserializeFailedTest.php
  tests/Unit/Store/DoctrineDbalStoreTest.php
  tests/Unit/Store/DoctrineDbalStreamTest.php
  tests/Unit/Store/DoctrineHelperTest.php
Labels: enhancement

#567 [Benchmark] Add loading only 1 event
  .github/workflows/benchmark.yml
  baseline.xml
  tests/Benchmark/PersonalDataBench.php
  tests/Benchmark/SimpleSetupBench.php
Labels: enhancement

#568 add payload cryptographer for snapshots too
  baseline.xml
  deptrac.yaml
  docs/pages/personal_data.md
  phpstan-baseline.neon
  src/Cryptography/CryptographicHydrator.php
  src/Cryptography/EventPayloadCryptographer.php
  src/Cryptography/PayloadCryptographer.php
  src/Cryptography/SnapshotPayloadCryptographer.php
  src/Cryptography/UnsupportedClass.php
  src/Metadata/AggregateRoot/AggregateRootMetadata.php
  src/Metadata/AggregateRoot/AttributeAggregateRootMetadataFactory.php
  src/Metadata/AggregateRoot/MissingDataSubjectId.php
  src/Metadata/AggregateRoot/MultipleDataSubjectId.php
  src/Metadata/AggregateRoot/PropertyMetadata.php
  src/Metadata/AggregateRoot/SubjectIdAndPersonalDataConflict.php
  src/Metadata/Event/AttributeEventMetadataFactory.php
  src/Metadata/Event/SubjectIdAndPersonalDataConflict.php
  src/Serializer/DefaultEventSerializer.php
  src/Snapshot/DefaultSnapshotStore.php
  tests/Benchmark/PersonalDataBench.php
  tests/Integration/PersonalData/PersonalDataTest.php
  tests/Integration/PersonalData/Profile.php
  tests/Unit/Cryptography/CryptographicHydratorTest.php
  tests/Unit/Cryptography/EventPayloadCryptographerTest.php
  tests/Unit/Cryptography/SnapshotPayloadCryptographerTest.php
  tests/Unit/Fixture/ProfileWithSnapshot.php
  tests/Unit/Metadata/Aggregate/AttributeAggregateMetadataFactoryTest.php
  tests/Unit/Metadata/Event/AttributeEventMetadataFactoryTest.php
Labels: enhancement

#572 move cryptography into hydrator
  baseline.xml
  composer.json
  composer.lock
  docs/pages/personal_data.md
  phpstan-baseline.neon
  src/Attribute/DataSubjectId.php
  src/Attribute/PersonalData.php
  src/Cryptography/Cipher/Cipher.php
  src/Cryptography/Cipher/CipherKey.php
  src/Cryptography/Cipher/CipherKeyFactory.php
  src/Cryptography/Cipher/CreateCipherKeyFailed.php
  src/Cryptography/Cipher/DecryptionFailed.php
  src/Cryptography/Cipher/EncryptionFailed.php
  src/Cryptography/Cipher/MethodNotSupported.php
  src/Cryptography/Cipher/OpensslCipher.php
  src/Cryptography/Cipher/OpensslCipherKeyFactory.php
  src/Cryptography/CryptographicHydrator.php
  src/Cryptography/DoctrineCipherKeyStore.php
  src/Cryptography/EventPayloadCryptographer.php
  src/Cryptography/MissingSubjectId.php
  src/Cryptography/PayloadCryptographer.php
  src/Cryptography/SnapshotPayloadCryptographer.php
  src/Cryptography/Store/CipherKeyNotExists.php
  src/Cryptography/Store/CipherKeyStore.php
  src/Cryptography/Store/InMemoryCipherKeyStore.php
  src/Cryptography/UnsupportedClass.php
  src/Cryptography/UnsupportedSubjectId.php
  src/Metadata/AggregateRoot/AggregateRootMetadata.php
  src/Metadata/AggregateRoot/AttributeAggregateRootMetadataFactory.php
  src/Metadata/AggregateRoot/PropertyMetadata.php
  src/Metadata/Event/AttributeEventMetadataFactory.php
  src/Metadata/Event/EventMetadata.php
  src/Metadata/Event/PropertyMetadata.php
  src/Serializer/DefaultEventSerializer.php
  src/Snapshot/DefaultSnapshotStore.php
  tests/Benchmark/BasicImplementation/Events/EmailChanged.php
  tests/Benchmark/BasicImplementation/Events/ProfileCreated.php
  tests/Benchmark/PersonalDataBench.php
  tests/Integration/PersonalData/Events/NameChanged.php
  tests/Integration/PersonalData/Events/ProfileCreated.php
  tests/Integration/PersonalData/PersonalDataTest.php
  tests/Integration/PersonalData/Processor/DeletePersonalDataProcessor.php
  tests/Integration/PersonalData/Profile.php
  tests/Unit/Cryptography/Cipher/CreateCipherKeyFailedTest.php
  tests/Unit/Cryptography/Cipher/DecryptionFailedTest.php
  tests/Unit/Cryptography/Cipher/EncryptionFailedTest.php
  tests/Unit/Cryptography/Cipher/OpensslCipherKeyFactoryTest.php
  tests/Unit/Cryptography/Cipher/OpensslCipherTest.php
  tests/Unit/Cryptography/CryptographicHydratorTest.php
  tests/Unit/Cryptography/EventPayloadCryptographerTest.php
  tests/Unit/Cryptography/MissingSubjectIdTest.php
  tests/Unit/Cryptography/SnapshotPayloadCryptographerTest.php
  tests/Unit/Cryptography/Store/CipherKeyNotExistsTest.php
  tests/Unit/Cryptography/Store/InMemoryCipherKeyStoreTest.php
  tests/Unit/Cryptography/UnsupportedSubjectIdTest.php
  tests/Unit/Fixture/EmailChanged.php
  tests/Unit/Fixture/ProfileWithSnapshot.php
  tests/Unit/Metadata/Aggregate/AttributeAggregateMetadataFactoryTest.php
  tests/Unit/Metadata/Event/AttributeEventMetadataFactoryTest.php
Labels: enhancement

#575 improve aggregate id argument resolver
  docs/pages/getting_started.md
  docs/pages/subscription.md
  src/Subscription/Subscriber/ArgumentResolver/AggregateIdArgumentResolver.php
  tests/Benchmark/BasicImplementation/Projection/ProfileProjector.php
  tests/Integration/Subscription/Subscriber/ErrorProducerSubscriber.php
  tests/Integration/Subscription/Subscriber/ProfileNewProjection.php
  tests/Integration/Subscription/Subscriber/ProfileProcessor.php
  tests/Integration/Subscription/Subscriber/ProfileProjection.php
  tests/Unit/Subscription/Subscriber/ArgumentResolver/AggregateIdArgumentResolverTest.php
Labels: enhancement

#574 add subscription engine result
  docs/pages/cli.md
  src/Console/Command/SubscriptionBootCommand.php
  src/Subscription/Engine/DefaultSubscriptionEngine.php
  src/Subscription/Engine/Error.php
  src/Subscription/Engine/ProcessedResult.php
  src/Subscription/Engine/Result.php
  src/Subscription/Engine/SubscriptionEngine.php
  src/Subscription/Store/DoctrineSubscriptionStore.php
  src/Subscription/Store/LockableSubscriptionStore.php
  tests/Integration/Subscription/SubscriptionTest.php
  tests/Unit/Subscription/Engine/DefaultSubscriptionEngineTest.php
Labels: enhancement

#507 update repository, snapshots, split stream and upcast docs
  README.md
  docs/mkdocs.yml
  docs/pages/cli.md
  docs/pages/clock.md
  docs/pages/event_bus.md
  docs/pages/events.md
  docs/pages/getting_started.md
  docs/pages/index.md
  docs/pages/message.md
  docs/pages/message_decorator.md
  docs/pages/normalizer.md
  docs/pages/outbox.md
  docs/pages/personal_data.md
  docs/pages/repository.md
  docs/pages/snapshots.md
  docs/pages/split_stream.md
  docs/pages/store.md
  docs/pages/subscription.md
  docs/pages/upcasting.md
Labels: documentation

#578 improve store criteria
  baseline.xml
  docs/pages/store.md
  phpstan-baseline.neon
  src/Console/Command/ShowAggregateCommand.php
  src/Console/Command/WatchCommand.php
  src/Repository/DefaultRepository.php
  src/Store/Criteria.php
  src/Store/Criteria/AggregateIdCriterion.php
  src/Store/Criteria/AggregateNameCriterion.php
  src/Store/Criteria/ArchivedCriterion.php
  src/Store/Criteria/Criteria.php
  src/Store/Criteria/CriteriaBuilder.php
  src/Store/Criteria/CriterionNotFound.php
  src/Store/Criteria/FromIndexCriterion.php
  src/Store/Criteria/FromPlayheadCriterion.php
  src/Store/DoctrineDbalStore.php
  src/Store/Store.php
  src/Store/UnsupportedCriterion.php
  src/Subscription/Engine/DefaultSubscriptionEngine.php
  tests/Unit/Console/Command/ShowAggregateCommandTest.php
  tests/Unit/Repository/DefaultRepositoryTest.php
  tests/Unit/Store/Crtieria/CriteriaBuilderTest.php
  tests/Unit/Store/Crtieria/CriteriaTest.php
  tests/Unit/Store/DoctrineDbalStoreTest.php
  tests/Unit/Subscription/Engine/DefaultSubscriptionEngineTest.php
Labels: enhancement, BC-Break

#580 Typo: fix immutable typo
  docs/pages/events.md
Labels: documentation

#582 remove doctrine helper and move logic into doctrine dbal store stream
  baseline.xml
  phpstan-baseline.neon
  src/Store/DoctrineDbalStoreStream.php
  src/Store/DoctrineHelper.php
  tests/Unit/Store/DoctrineHelperTest.php
Labels: BC-Break

#581 make aggregate id type configurable between uuid and string
  docs/pages/aggregate_id.md
  docs/pages/message_decorator.md
  docs/pages/store.md
  docs/pages/subscription.md
  src/Store/DoctrineDbalStore.php
  tests/Benchmark/PersonalDataBench.php
  tests/Benchmark/blackfire.php
  tests/Integration/BankAccountSplitStream/AccountId.php
  tests/Integration/BankAccountSplitStream/IntegrationTest.php
  tests/Integration/BasicImplementation/BasicIntegrationTest.php
  tests/Integration/BasicImplementation/ProfileId.php
  tests/Integration/PersonalData/PersonalDataTest.php
  tests/Integration/PersonalData/ProfileId.php
  tests/Integration/Store/ProfileId.php
  tests/Integration/Store/StoreTest.php
  tests/Integration/Subscription/ProfileId.php
  tests/Integration/Subscription/SubscriptionTest.php
  tests/Unit/Store/DoctrineDbalStoreTest.php
Labels: enhancement, BC-Break

#585 add throw on error subscription engine decorator
  docs/pages/subscription.md
  src/Subscription/Engine/ErrorDetected.php
  src/Subscription/Engine/ThrowOnErrorSubscriptionEngine.php
  tests/Unit/Subscription/Engine/ErrorDetectedTest.php
  tests/Unit/Subscription/Engine/ThrowOnErrorSubscriptionEngineTest.php
Labels: enhancement

#584 refactor uuid implementation & add a test uuid factory
  docs/pages/aggregate_id.md
  docs/pages/getting_started.md
  docs/pages/repository.md
  docs/pages/testing.md
  src/Aggregate/RamseyUuidV7Behaviour.php
  src/Aggregate/Uuid.php
  src/Test/IncrementalRamseyUuidFactory.php
  tests/Benchmark/BasicImplementation/ProfileId.php
  tests/Benchmark/PersonalDataBench.php
  tests/Benchmark/SimpleSetupBench.php
  tests/Benchmark/SnapshotsBench.php
  tests/Benchmark/SplitStreamBench.php
  tests/Benchmark/SubscriptionEngineBench.php
  tests/Benchmark/blackfire.php
  tests/Integration/BankAccountSplitStream/AccountId.php
  tests/Integration/BankAccountSplitStream/IntegrationTest.php
  tests/Integration/BasicImplementation/BasicIntegrationTest.php
  tests/Integration/BasicImplementation/ProfileId.php
  tests/Integration/PersonalData/PersonalDataTest.php
  tests/Integration/PersonalData/ProfileId.php
  tests/Integration/Store/ProfileId.php
  tests/Integration/Store/StoreTest.php
  tests/Integration/Subscription/ProfileId.php
  tests/Integration/Subscription/SubscriptionTest.php
  tests/Unit/Aggregate/UuidTest.php
  tests/Unit/Test/IncrementalRamseyUuidFactoryTest.php
Labels: enhancement

#586 throw an exception if duplicated subscriber id exists
  src/Subscription/Subscriber/DuplicateSubscriberId.php
  src/Subscription/Subscriber/MetadataSubscriberAccessorRepository.php
  tests/Unit/Subscription/Subscriber/MetadataSubscriberAccessorRepositoryTest.php
Labels: bug

#587 move event bus dispatch outside of repository transaction
  docs/pages/repository.md
  src/Repository/DefaultRepository.php
Labels: BC-Break

#589 fix building docs
  .github/workflows/docs-build-try.yml
  docs/mkdocs.yml
  docs/pages/message_decorator.md
  docs/pages/store.md
  docs/pages/subscription.md
  docs/pages/testing.md
  docs/requirements.txt
Labels: dependencies

#588 Add RunSubscriptionEngineRepository
  deptrac.yaml
  docs/pages/getting_started.md
  docs/pages/subscription.md
  src/Subscription/Engine/AlreadyProcessing.php
  src/Subscription/Engine/DefaultSubscriptionEngine.php
  src/Subscription/Engine/SubscriptionEngine.php
  src/Subscription/Repository/RunSubscriptionEngineRepository.php
  src/Subscription/Repository/RunSubscriptionEngineRepositoryManager.php
  tests/Integration/BasicImplementation/BasicIntegrationTest.php
  tests/Integration/BasicImplementation/Processor/SendEmailProcessor.php
  tests/Unit/Subscription/DummySubscriptionStore.php
  tests/Unit/Subscription/Engine/DefaultSubscriptionEngineTest.php
  tests/Unit/Subscription/Repository/RunSubscriptionEngineRepositoryManagerTest.php
  tests/Unit/Subscription/Repository/RunSubscriptionEngineRepositoryTest.php
Labels: enhancement

#593 Add links to external sites in the navigation
  docs/mkdocs.yml
  docs/pages/subscription.md
Labels: documentation

#594 fix finish flag in subscription engine
  src/Console/Command/SubscriptionBootCommand.php
  src/Subscription/Engine/CatchUpSubscriptionEngine.php
  src/Subscription/Engine/DefaultSubscriptionEngine.php
  src/Subscription/Engine/ProcessedResult.php
  tests/Unit/Subscription/Engine/DefaultSubscriptionEngineTest.php
Labels: bug

#595 fix missing default sleep time in subscription boot command
  src/Console/Command/SubscriptionBootCommand.php
Labels: bug

#598 move archive logic into store
  baseline.xml
  src/Repository/DefaultRepository.php
  src/Store/ArchivableStore.php
  src/Store/DoctrineDbalStore.php
  tests/Unit/Repository/DefaultRepositoryTest.php
  tests/Unit/Store/DoctrineDbalStoreTest.php
Labels: BC-Break

#569 Add Upgrade path to v3
  UPGRADE-3.0.md
  docs/mkdocs.yml
  docs/pages/UPGRADE-3.0.md
Labels: documentation

#599 fix dbal connection setup in docs
  docs/pages/getting_started.md
  docs/pages/store.md
Labels: documentation

#602 deprecate doctrine subscriber and add doctrine listener
  baseline.xml
  src/Schema/DoctrineSchemaListener.php
  src/Schema/DoctrineSchemaSubscriber.php
  tests/Unit/Schema/DoctrineSchemaListenerTest.php
Labels: enhancement
