Repository patchlevel/event-sourcing, pull requests merged in 2025-01, with the labels that each got.

#666 Update phpstan to v2
  composer.json
  composer.lock
  phpstan-baseline.neon
Labels: dependencies

#644 Add command bus, Drop PHP 8.1
  .github/workflows/unit.yml
  baseline.xml
  composer.json
  composer.lock
  deptrac.yaml
  docs/mkdocs.yml
  docs/pages/command_bus.md
  src/Attribute/Handle.php
  src/Attribute/Inject.php
  src/CommandBus/AggregateHandlerProvider.php
  src/CommandBus/ChainHandlerProvider.php
  src/CommandBus/CommandBus.php
  src/CommandBus/Handler/AggregateIdNotFound.php
  src/CommandBus/Handler/CreateAggregateHandler.php
  src/CommandBus/Handler/DefaultParameterResolver.php
  src/CommandBus/Handler/ParameterResolver.php
  src/CommandBus/Handler/ServiceNotResolvable.php
  src/CommandBus/Handler/UpdateAggregateHandler.php
  src/CommandBus/HandlerDescriptor.php
  src/CommandBus/HandlerFinder.php
  src/CommandBus/HandlerNotFound.php
  src/CommandBus/HandlerProvider.php
  src/CommandBus/HandlerReference.php
  src/CommandBus/InvalidHandleMethod.php
  src/CommandBus/MultipleHandlersFound.php
  src/CommandBus/ServiceHandlerProvider.php
  src/CommandBus/ServiceLocator.php
  src/CommandBus/ServiceNotFound.php
  src/CommandBus/SyncCommandBus.php
  tests/Integration/BasicImplementation/BasicIntegrationTest.php
  tests/Integration/BasicImplementation/Command/ChangeProfileName.php
  tests/Integration/BasicImplementation/Command/CreateProfile.php
  tests/Integration/BasicImplementation/ProfileWithCommands.php
  tests/Integration/BasicImplementation/Projection/ProfileProjector.php
  tests/Unit/CommandBus/AggregateHandlerProviderTest.php
  tests/Unit/CommandBus/ChainHandlerProviderTest.php
  tests/Unit/CommandBus/Handler/CreateAggregateHandlerTest.php
  tests/Unit/CommandBus/Handler/DefaultParameterResolverTest.php
  tests/Unit/CommandBus/Handler/UpdateAggregateHandlerTest.php
  tests/Unit/CommandBus/HandlerDescriptorTest.php
  tests/Unit/CommandBus/HandlerFinderTest.php
  tests/Unit/CommandBus/ServiceHandlerProviderTest.php
  tests/Unit/CommandBus/ServiceLocatorTest.php
  tests/Unit/CommandBus/SyncCommandBusTest.php
  tests/Unit/Fixture/ActivateProfile.php
  tests/Unit/Fixture/ChangeProfileName.php
  tests/Unit/Fixture/CreateProfile.php
  tests/Unit/Fixture/ProfileWithHandler.php
Labels: enhancement

#673 improve stream store
  baseline.xml
  docs/pages/aggregate.md
  docs/pages/store.md
  phpstan-baseline.neon
  src/Aggregate/InvalidAggregateStreamName.php
  src/Message/Translator/AggregateToStreamHeaderTranslator.php
  src/Repository/DefaultRepository.php
  src/Repository/DefaultRepositoryManager.php
  src/Store/Criteria/CriteriaBuilder.php
  src/Store/Criteria/StreamCriterion.php
  src/Store/Criteria/ToPlayheadCriterion.php
  src/Store/Header/EventIdHeader.php
  src/Store/Header/PlayheadHeader.php
  src/Store/Header/RecordedOnHeader.php
  src/Store/Header/StreamNameHeader.php
  src/Store/InMemoryStore.php
  src/Store/InvalidStreamName.php
  src/Store/StreamDoctrineDbalStore.php
  src/Store/StreamDoctrineDbalStoreStream.php
  src/Store/StreamStore.php
  tests/Integration/BankAccountSplitStream/IntegrationTest.php
  tests/Integration/Store/StreamDoctrineDbalStoreTest.php
  tests/Unit/Store/InMemoryStoreTest.php
  tests/Unit/Store/StreamDoctrineDbalStoreTest.php
Labels: enhancement

#674 add read only store
  docs/pages/aggregate.md
  docs/pages/store.md
  src/Store/ReadOnlyStore.php
  src/Store/StoreIsReadOnly.php
  src/Store/StreamReadOnlyStore.php
  tests/Unit/Store/ReadOnlyStoreTest.php
  tests/Unit/Store/StreamReadOnlyStoreTest.php
Labels: enhancement

#659 Lookup
  baseline.xml
  docs/pages/subscription.md
  phpstan-baseline.neon
  src/Serializer/DefaultEventSerializer.php
  src/Store/Criteria/ToIndexCriterion.php
  src/Store/DoctrineDbalStore.php
  src/Store/DoctrineDbalStoreStream.php
  src/Store/Header/IndexHeader.php
  src/Store/StreamDoctrineDbalStore.php
  src/Store/StreamDoctrineDbalStoreStream.php
  src/Subscription/Lookup/Lookup.php
  src/Subscription/Lookup/MessageNotFound.php
  src/Subscription/Subscriber/ArgumentResolver/LookupResolver.php
  tests/Integration/Subscription/Events/AdminPromoted.php
  tests/Integration/Subscription/Events/NameChanged.php
  tests/Integration/Subscription/Profile.php
  tests/Integration/Subscription/Subscriber/LookupSubscriber.php
  tests/Integration/Subscription/SubscriptionTest.php
  tests/Unit/Store/DoctrineDbalStoreTest.php
  tests/Unit/Store/DoctrineDbalStreamTest.php
  tests/Unit/Store/StreamDoctrineDbalStoreTest.php
  tests/Unit/Store/StreamDoctrineDbalStreamTest.php
  tests/Unit/Subscription/Lookup/LookupTest.php
  tests/Unit/Subscription/Subscriber/ArgumentResolver/LookupResolverTest.php
Labels: enhancement

#675 allow multiple wildcards in stream store
  baseline.xml
  src/Message/Message.php
  src/Store/Criteria/StreamCriterion.php
  src/Store/StreamDoctrineDbalStore.php
  tests/Integration/Store/StreamDoctrineDbalStoreTest.php
  tests/Unit/Store/StreamDoctrineDbalStoreTest.php
Labels: enhancement

#676 add event id criteria
  src/Store/Criteria/EventIdCriterion.php
  src/Store/StreamDoctrineDbalStore.php
Labels: enhancement

#677 add "keep_index" option in stream store
  docs/pages/store.md
  src/Store/StreamDoctrineDbalStore.php
  tests/Integration/Store/StreamDoctrineDbalStoreTest.php
Labels: enhancement

#678 improve flatten args in error context transformer
  baseline.xml
  phpstan-baseline.neon
  src/Subscription/SubscriptionError.php
  src/Subscription/ThrowableToErrorContextTransformer.php
  tests/Unit/Subscription/ErrorContextTest.php
Labels: bug
