Repository patchlevel/event-sourcing, pull requests merged in 2025-03, with the labels that each got.

#708 add missing index header
  src/Metadata/Message/MessageHeaderRegistry.php
Labels: bug

#709 add missing index header in registry
  src/Metadata/Message/MessageHeaderRegistry.php
Labels: bug

#713 handle missing subscriber in subscription engine booting & pause
  src/Subscription/Engine/DefaultSubscriptionEngine.php
  tests/Unit/Subscription/Engine/DefaultSubscriptionEngineTest.php
Labels: bug

#715 fix limit 0 in show command & fix show aggregate with stream store
  src/Console/Command/ShowAggregateCommand.php
  src/Console/Command/ShowCommand.php
Labels: bug

#724 Update various dependencies
  baseline.xml
  composer.json
  composer.lock
  tests/Unit/Store/InMemoryStoreTest.php
Labels: dependencies

#721 Add subscriber information to `event-sourcing:debug`
  src/Console/Command/DebugCommand.php
  tests/Unit/Console/Command/DebugCommandTest.php
Labels: enhancement

#717 Add ConsoleLogger on Watch Command
  src/Console/Command/WatchCommand.php
  tests/Unit/Console/Command/WatchCommandTest.php
Labels: enhancement

#728 Add GapDetection as MessageLoader try to ensure no events are skipped in subscriptions
  baseline.xml
  docs/pages/subscription.md
  phpstan-baseline.neon
  src/Subscription/Engine/GapResolverStoreMessageLoader.php
  src/Subscription/Engine/GeneratorStream.php
  tests/Integration/Subscription/SubscriptionTest.php
  tests/Unit/Subscription/Engine/GapResolverStoreMessageLoaderTest.php
Labels: enhancement
