Repository patchlevel/event-sourcing, pull requests merged in 2025-02, with the labels that each got.

#684 fix: remove queue in command bus
  docs/pages/command_bus.md
  phpstan-baseline.neon
  src/CommandBus/SyncCommandBus.php
  src/Subscription/ThrowableToErrorContextTransformer.php
Labels: bug

#685 Inject event dispatcher to worker
  composer.json
  composer.lock
  src/Console/Command/SubscriptionBootCommand.php
  src/Console/Command/SubscriptionRunCommand.php
Labels: enhancement

#687 Use reflection for accessing child aggregates, add test case which covers private child aggregates
  baseline.xml
  src/Aggregate/AggregateRootAttributeBehaviour.php
  tests/Integration/ChildAggregate/ChildAggregateIntegrationTest.php
  tests/Integration/ChildAggregate/Events/ViewTracked.php
  tests/Integration/ChildAggregate/Profile.php
  tests/Integration/ChildAggregate/Views.php
Labels: enhancement

#682 Update psalm to v6
  baseline.xml
  composer.json
  composer.lock
  tests/Unit/Subscription/ErrorContextTest.php
Labels: dependencies

#628 add php84 support
  .github/workflows/integration.yml
  .github/workflows/unit.yml
  composer.json
  composer.lock
Labels: enhancement

#699 add on failed hook in subscription engine
  baseline.xml
  docs/pages/subscription.md
  src/Attribute/OnFailed.php
  src/Metadata/Subscriber/AttributeSubscriberMetadataFactory.php
  src/Metadata/Subscriber/DuplicateFailedMethod.php
  src/Metadata/Subscriber/SubscriberMetadata.php
  src/Subscription/Engine/DefaultSubscriptionEngine.php
  src/Subscription/Subscriber/MetadataSubscriberAccessor.php
  tests/Integration/Subscription/Subscriber/ErrorProducerWithSelfRecoverySubscriber.php
  tests/Integration/Subscription/SubscriptionTest.php
  tests/Unit/Subscription/Engine/DefaultSubscriptionEngineTest.php
  tests/Unit/Subscription/RetryStrategy/ClockBasedRetryStrategyTest.php
Labels: enhancement

#701 Dont allow subscribing same event multiple times in one subscriber
  src/Metadata/Subscriber/AttributeSubscriberMetadataFactory.php
  src/Metadata/Subscriber/DuplicateSubscribeMethod.php
  tests/Unit/Metadata/Subscriber/AttributeSubscriberMetadataFactoryTest.php
  tests/Unit/Subscription/Subscriber/MetadataSubscriberAccessorTest.php
Labels: bug, BC-Break
